[project]
name = "agent-security"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
learner = [
    "jupyter",
    "ipykernel",
    "mcp>=2.2,<3",
    "openai-agents>=0.22.2,<0.23",
    "pydantic>=2.11,<3"
]
contributor = [
    "agent-security[learner]",
    "pytest",
    "nbclient",
    "nbformat",
]

[tool.setuptools]
py-modules = []
packages = []
