[project]
name = "agent-security"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
learner = [
    "jupyter",
    "ipykernel",
    "mcp"
]
contributor = [
    "agent-security[learner]",
    "pytest",
    "nbclient",
    "nbformat",
]

[tool.setuptools]
py-modules = []
packages = []
