const lesson = (id, level, step, title, summary, outcome, folder, fileStem, checkpoint) => ({
  id,
  level,
  step,
  title,
  summary,
  outcome,
  material: `curriculum/${folder}/README.md`,
  lab: `curriculum/${folder}/${fileStem}.py`,
  notebook: `curriculum/${folder}/${fileStem}.ipynb`,
  checkpoint,
});

export const publishedLessons = [
  lesson("b1", "Beginner", "01", "Security foundations and tool policy", "Place authorization, approval, budgets, and audit controls at trusted boundaries.", "Design a narrow action contract and prove that unauthorized side effects are rejected.", "beginner/01-tool-policy", "01_tool_policy", {
    prompt: "A model proposes a destructive action. Which component may authorize it?",
    options: ["The model prompt", "A deterministic policy at the action boundary", "Retrieved content"],
    correct: 1,
    explanation: "Only trusted application policy can grant authority; prompts and retrieved text are inputs, not policy decisions.",
  }),
  lesson("b2", "Beginner", "02", "Prompt injection and untrusted content", "Separate instructions from documents, tool output, and memory.", "Contain an indirect injection even when simple marker detection misses it.", "beginner/02-prompt-injection", "02_prompt_injection", {
    prompt: "A retrieved document says to ignore policy and send a secret. What authority does it have?",
    options: ["None; it remains untrusted evidence", "System-level authority", "Tool-administrator authority"],
    correct: 0,
    explanation: "External content may inform an answer but cannot authorize a tool call or change system policy.",
  }),
  lesson("b3", "Beginner", "03", "Secure research agent", "Combine provenance, evidence ranking, narrow tools, and policy enforcement.", "Return traceable evidence while refusing unsafe capabilities and poisoned instructions.", "beginner/03-secure-research-agent", "03_secure_research_agent", {
    prompt: "What makes a research answer auditable?",
    options: ["A fluent explanation", "Stable evidence identifiers and policy receipts", "A larger context window"],
    correct: 1,
    explanation: "Auditability comes from attributable evidence and observable policy decisions, not answer fluency.",
  }),
  lesson("i1", "Intermediate", "01", "Identity propagation", "Preserve user, workload, tenant, resource, operation, and delegated scope.", "Reject tenant swaps, audience confusion, and authority widening across service hops.", "intermediate/01-identity-propagation", "01_identity_propagation", {
    prompt: "A service receives both a signed principal and a tenant supplied in tool arguments. Which tenant is authoritative?",
    options: ["The tool argument", "The trusted identity context", "Whichever appears first"],
    correct: 1,
    explanation: "Authorization scope must be derived from authenticated application state, never model-controlled arguments.",
  }),
  lesson("i2", "Intermediate", "02", "MCP gateway security", "Treat discovery as metadata and independently authenticate and authorize every invocation.", "Enforce server trust, scopes, schemas, limits, and privacy-aware receipts.", "intermediate/02-mcp-gateway", "02_mcp_gateway", {
    prompt: "A discovered MCP server advertises an admin tool. What should the gateway do?",
    options: ["Trust discovery", "Require server trust and caller authorization", "Forward the caller token"],
    correct: 1,
    explanation: "Discovery does not prove server identity, tool safety, or caller authority.",
  }),
  lesson("i3", "Intermediate", "03", "Incident response and recovery", "Contain suspicious runs, revoke capabilities, and recover with safe replay.", "Prevent duplicate effects and reauthorize changed state before resuming.", "intermediate/03-incident-recovery", "03_incident_recovery", {
    prompt: "Why must a replay reuse the original idempotency key?",
    options: ["To improve prompts", "To prevent a second external side effect", "To replace authorization"],
    correct: 1,
    explanation: "Idempotency deduplicates uncertain retries; authorization is still evaluated independently.",
  }),
  lesson("a1", "Advanced", "01", "Security attack evaluation", "Turn versioned attack cases and observable trajectories into release evidence.", "Measure severe failures, traceability, and valid-task blocking with correct denominators.", "advanced/01-attack-evaluation", "01_attack_evaluation", {
    prompt: "What should block release even if the average score improves?",
    options: ["One severe unauthorized action", "A formatting difference", "A slower harmless fixture"],
    correct: 0,
    explanation: "A severe security failure is a release blocker and must not be hidden by aggregate averages.",
  }),
  lesson("a2", "Advanced", "02", "Multi-agent delegation", "Constrain child roles, scopes, budgets, state, and termination conditions.", "Prove a delegated worker cannot exceed its parent authority.", "advanced/02-multi-agent-security", "02_multi_agent_security", {
    prompt: "Which delegation relationship must always hold?",
    options: ["Child authority contains parent authority", "Child authority is a subset of parent authority", "All agents share credentials"],
    correct: 1,
    explanation: "Delegation attenuates authority; it must never amplify the parent’s capabilities.",
  }),
  lesson("a3", "Advanced", "03", "Production readiness", "Bind governance, ownership, rollback drills, and attack results into a release gate.", "Issue an evidence-based production decision with named residual-risk owners.", "advanced/03-production-gate", "03_production_gate", {
    prompt: "Which evidence is required before granting production autonomy?",
    options: ["A successful demo", "A rollback drill and named control owners", "A model self-assessment"],
    correct: 1,
    explanation: "Production authority requires independently verified controls, recovery readiness, and accountable ownership.",
  }),
];

export const roadmapTracks = [
  { level: "Foundation", range: "01–07", status: "Reading sequence", summary: "Trust boundaries, threat models, invariants, narrow tools, authorization, injection, and evidence security." },
  { level: "State & execution", range: "08–17", status: "Pilot labs", summary: "Memory, durable state, identity, credentials, sandboxing, egress, poisoned output, RAG, MCP, and approval." },
  { level: "Distributed adversaries", range: "18–27", status: "Pilot labs", summary: "Delegation, cross-agent injection, cascading failures, protocols, supply chain, fuzzing, evaluation, and detection." },
  { level: "Enterprise operations", range: "28–36", status: "Pilot labs", summary: "Long-running agents, revocation, incidents, forensics, release gates, governance, architecture, and capstone." },
];

const road = (number, level, title, folder, status, evidence) => ({ number, level, title, folder, status, evidence });

export const roadmapCourses = [
  road("01", "Foundation", "Architecture and trust boundaries", "beginner/01-agent-security-architecture-and-trust-boundaries", "Reading", "README · needs lab, notebook, tests"),
  road("02", "Foundation", "Threat modeling agentic systems", "beginner/02-threat-modeling-agentic-systems", "Reading", "README · needs lab, notebook, tests"),
  road("03", "Foundation", "Security invariants and blast radius", "beginner/03-security-invariants-and-blast-radius", "Reading", "README · needs lab, notebook, tests"),
  road("04", "Foundation", "Secure tool and action interfaces", "beginner/04-secure-tool-and-action-interface-design", "Reading", "README · needs focused lab, notebook, tests"),
  road("05", "Foundation", "Authorization, approval, and least privilege", "beginner/05-authorization-approval-and-least-privilege", "Reading", "README · needs focused lab, notebook, tests"),
  road("06", "Foundation", "Prompt injection and untrusted content", "beginner/06-prompt-injection-and-untrusted-content", "Reading", "README · needs focused lab, notebook, tests"),
  road("07", "Foundation", "Context and evidence security", "beginner/07-context-and-evidence-security", "Reading", "README · needs lab, notebook, tests"),
  road("08", "State & execution", "Agent memory security", "intermediate/08-agent-memory-security", "Pilot", "README · lab · notebook · needs deeper tests"),
  road("09", "State & execution", "Checkpoint and durable execution security", "intermediate/09-state-checkpoint-and-durable-execution-security", "Pilot", "README · notebook · needs course adapter and tests"),
  road("10", "State & execution", "Agent identity and delegated authority", "intermediate/10-agent-identity-and-delegated-authority", "Planned", "Release contract · needs lab, notebook, tests"),
  road("11", "State & execution", "Secrets and credential security", "intermediate/11-secrets-and-credential-security", "Pilot", "README · lab · needs notebook and tests"),
  road("12", "State & execution", "Filesystem, execution, and sandbox security", "intermediate/12-filesystem-code-execution-and-sandbox-security", "Planned", "Release contract · needs lab, notebook, tests"),
  road("13", "State & execution", "Network egress, SSRF, and resources", "intermediate/13-network-egress-ssrf-and-external-resource-security", "Pilot", "README · lab · notebook · needs deeper tests"),
  road("14", "State & execution", "Tool-result and output poisoning", "intermediate/14-tool-result-and-output-poisoning", "Pilot", "README · lab · needs notebook and tests"),
  road("15", "State & execution", "Agentic RAG security", "intermediate/15-agentic-rag-security", "Planned", "Release contract · needs lab, notebook, tests"),
  road("16", "State & execution", "MCP security", "intermediate/16-mcp-security", "Pilot", "README · lab · notebook · needs protocol update and tests"),
  road("17", "State & execution", "Human-in-the-loop security", "intermediate/17-human-in-the-loop-security", "Planned", "Release contract · needs lab, notebook, tests"),
  road("18", "Distributed adversaries", "Multi-agent delegation security", "advanced/18-multi-agent-delegation-security", "Pilot", "README · notebook · needs course adapter and tests"),
  road("19", "Distributed adversaries", "Cross-agent injection and message poisoning", "advanced/19-cross-agent-prompt-injection-and-message-poisoning", "Planned", "Release contract · needs lab, notebook, tests"),
  road("20", "Distributed adversaries", "Cascading failures and blast radius", "advanced/20-cascading-failures-and-blast-radius-control", "Planned", "Release contract · needs lab, notebook, tests"),
  road("21", "Distributed adversaries", "Agent-to-agent (A2A) security", "advanced/21-agent-to-agent-a2a-security", "Planned", "A2A 1.0 contract · needs lab, notebook, tests"),
  road("22", "Distributed adversaries", "Protocol composition security", "advanced/22-protocol-composition-security", "Planned", "Release contract · needs lab, notebook, tests"),
  road("23", "Distributed adversaries", "Agent supply-chain security", "advanced/23-agent-supply-chain-security", "Planned", "SLSA-aligned contract · needs lab, notebook, tests"),
  road("24", "Distributed adversaries", "Agent security testing and fuzzing", "advanced/24-agent-security-testing-and-fuzzing", "Planned", "Release contract · needs lab, notebook, tests"),
  road("25", "Distributed adversaries", "Red teaming and adversarial evaluation", "advanced/25-agent-red-teaming-and-adversarial-evaluation", "Pilot", "README · lab · notebook · needs deeper tests"),
  road("26", "Distributed adversaries", "Observability and runtime assurance", "advanced/26-agent-security-observability-and-runtime-assurance", "Planned", "Release contract · needs lab, notebook, tests"),
  road("27", "Distributed adversaries", "Threat hunting and anomaly detection", "advanced/27-threat-hunting-and-behavioral-anomaly-detection", "Planned", "Release contract · needs lab, notebook, tests"),
  road("28", "Enterprise operations", "Secure long-running agents", "enterprise-agent/28-secure-long-running-agents", "Planned", "Release contract · needs lab, notebook, tests"),
  road("29", "Enterprise operations", "Kill switches and safe degradation", "enterprise-agent/29-kill-switches-revocation-and-safe-degradation", "Pilot", "README · notebook · needs course adapter and tests"),
  road("30", "Enterprise operations", "Incident detection and containment", "enterprise-agent/30-agent-incident-detection-and-containment", "Pilot", "README · notebook · needs course adapter and tests"),
  road("31", "Enterprise operations", "Forensics, recovery, and safe replay", "enterprise-agent/31-agent-forensics-recovery-and-safe-replay", "Planned", "Release contract · needs lab, notebook, tests"),
  road("32", "Enterprise operations", "Release gates and production readiness", "enterprise-agent/32-security-release-gates-and-production-readiness", "Planned", "Release contract · needs lab, notebook, tests"),
  road("33", "Enterprise operations", "Agent security governance", "enterprise-agent/33-agent-security-governance", "Pilot", "README · lab · notebook · needs deeper tests"),
  road("34", "Enterprise operations", "Enterprise security architecture", "enterprise-agent/34-enterprise-agent-security-architecture", "Planned", "Release contract · needs lab, notebook, tests"),
  road("35", "Enterprise operations", "Architecture review workshop", "enterprise-agent/35-agent-security-architecture-review-workshop", "Planned", "Release contract · needs lab, notebook, tests"),
  road("36", "Enterprise operations", "Production secure-agent capstone", "enterprise-agent/36-production-secure-agent-capstone", "Pilot", "README · lab · needs notebook and integrated tests"),
];
