const lesson = (id, level, step, title, summary, outcome, folder, fileStem, checkpoint) => ({
  id,
  level,
  step,
  title,
  summary,
  outcome,
  material: `curriculum/${folder}/README.md`,
  lab: `curriculum/${folder}/${fileStem}.py`,
  notebook: `curriculum/${folder}/${fileStem}.ipynb`,
  checkpoint,
});

export const publishedLessons = [
  lesson("b1", "Beginner", "01", "Security foundations and tool policy", "Place authorization, approval, budgets, and audit controls at trusted boundaries.", "Design a narrow action contract and prove that unauthorized side effects are rejected.", "beginner/01-tool-policy", "01_tool_policy", {
    prompt: "An SDK validates a submit-claim schema and pauses for approval. What must still happen immediately before execution?",
    options: ["Trust the SDK result", "Reauthorize the authenticated actor, resources, and exact approved arguments under current policy", "Ask the model whether the action is safe"],
    correct: 1,
    explanation: "Schema validation and workflow approval are useful controls, but only trusted application policy can grant authority for the exact action at the effect boundary.",
  }),
  lesson("b2", "Beginner", "02", "Prompt injection and untrusted content", "Separate instructions from documents, tool output, and memory.", "Contain an indirect injection even when simple marker detection misses it.", "beginner/02-prompt-injection", "02_prompt_injection", {
    prompt: "A detector labels a retrieved internal document clean, and the run has a refund capability. What must still happen before execution?",
    options: ["Execute because both checks passed", "Authorize the exact proposed effect from current trusted identity, run, grant, source, policy, and time", "Ask the model to confirm the document is safe"],
    correct: 1,
    explanation: "Detection and authentic provenance are risk signals, not authority. Trusted application policy must resolve current evidence and authorize the exact effect at the execution boundary.",
  }),
  lesson("b3", "Beginner", "03", "Secure research agent", "Combine provenance, evidence ranking, narrow tools, and policy enforcement.", "Return traceable evidence while refusing unsafe capabilities and poisoned instructions.", "beginner/03-secure-research-agent", "03_secure_research_agent", {
    prompt: "What makes a research answer auditable?",
    options: ["A fluent explanation", "Stable evidence identifiers and policy receipts", "A larger context window"],
    correct: 1,
    explanation: "Auditability comes from attributable evidence and observable policy decisions, not answer fluency.",
  }),
  lesson("i1", "Intermediate", "01", "Identity propagation", "Preserve user, workload, tenant, resource, operation, and delegated scope.", "Reject tenant swaps, audience confusion, and authority widening across service hops.", "intermediate/01-identity-propagation", "01_identity_propagation", {
    prompt: "A service receives both a signed principal and a tenant supplied in tool arguments. Which tenant is authoritative?",
    options: ["The tool argument", "The trusted identity context", "Whichever appears first"],
    correct: 1,
    explanation: "Authorization scope must be derived from authenticated application state, never model-controlled arguments.",
  }),
  lesson("i2", "Intermediate", "02", "MCP gateway security", "Treat discovery as metadata and independently authenticate and authorize every invocation.", "Enforce server trust, scopes, schemas, limits, and privacy-aware receipts.", "intermediate/02-mcp-gateway", "02_mcp_gateway", {
    prompt: "A discovered MCP server advertises an admin tool. What should the gateway do?",
    options: ["Trust discovery", "Require server trust and caller authorization", "Forward the caller token"],
    correct: 1,
    explanation: "Discovery does not prove server identity, tool safety, or caller authority.",
  }),
  lesson("i3", "Intermediate", "03", "Incident response and recovery", "Contain suspicious runs, revoke capabilities, and recover with safe replay.", "Prevent duplicate effects and reauthorize changed state before resuming.", "intermediate/03-incident-recovery", "03_incident_recovery", {
    prompt: "Why must a replay reuse the original idempotency key?",
    options: ["To improve prompts", "To prevent a second external side effect", "To replace authorization"],
    correct: 1,
    explanation: "Idempotency deduplicates uncertain retries; authorization is still evaluated independently.",
  }),
  lesson("a1", "Advanced", "01", "Security attack evaluation", "Turn versioned attack cases and observable trajectories into release evidence.", "Measure severe failures, traceability, and valid-task blocking with correct denominators.", "advanced/01-attack-evaluation", "01_attack_evaluation", {
    prompt: "What should block release even if the average score improves?",
    options: ["One severe unauthorized action", "A formatting difference", "A slower harmless fixture"],
    correct: 0,
    explanation: "A severe security failure is a release blocker and must not be hidden by aggregate averages.",
  }),
  lesson("a2", "Advanced", "02", "Multi-agent delegation", "Constrain child roles, scopes, budgets, state, and termination conditions.", "Prove a delegated worker cannot exceed its parent authority.", "advanced/02-multi-agent-security", "02_multi_agent_security", {
    prompt: "Which delegation relationship must always hold?",
    options: ["Child authority contains parent authority", "Child authority is a subset of parent authority", "All agents share credentials"],
    correct: 1,
    explanation: "Delegation attenuates authority; it must never amplify the parent’s capabilities.",
  }),
  lesson("a3", "Advanced", "03", "Production readiness", "Bind governance, ownership, rollback drills, and attack results into a release gate.", "Issue an evidence-based production decision with named residual-risk owners.", "advanced/03-production-gate", "03_production_gate", {
    prompt: "Which evidence is required before granting production autonomy?",
    options: ["A successful demo", "A rollback drill and named control owners", "A model self-assessment"],
    correct: 1,
    explanation: "Production authority requires independently verified controls, recovery readiness, and accountable ownership.",
  }),
];

export const roadmapTracks = [
  { level: "Foundation", range: "01–07", status: "Reading sequence", summary: "Trust boundaries, threat models, invariants, narrow tools, authorization, injection, and evidence security." },
  { level: "State & execution", range: "01–10", status: "Pilot labs", summary: "Memory, durable state, identity, credentials, sandboxing, egress, poisoned output, RAG, MCP, and approval." },
  { level: "Distributed adversaries", range: "01–10", status: "Pilot labs", summary: "Delegation, cross-agent injection, cascading failures, protocols, supply chain, fuzzing, evaluation, and detection." },
  { level: "Enterprise operations", range: "01–09", status: "Pilot labs", summary: "Long-running agents, revocation, incidents, forensics, release gates, governance, architecture, and capstone." },
];

const road = (code, number, level, title, folder, status, evidence) => ({ code, number, level, title, folder, status, evidence });

export const roadmapCourses = [
  road("F01", "01", "Foundation", "Architecture and trust boundaries", "roadmap/beginner/01-agent-security-architecture-and-trust-boundaries", "Reading", "README · needs lab, notebook, tests"),
  road("F02", "02", "Foundation", "Threat modeling agentic systems", "roadmap/beginner/02-threat-modeling-agentic-systems", "Reading", "README · needs lab, notebook, tests"),
  road("F03", "03", "Foundation", "Security invariants and blast radius", "roadmap/beginner/03-security-invariants-and-blast-radius", "Reading", "README · needs lab, notebook, tests"),
  road("F04", "04", "Foundation", "Secure tool and action interfaces", "roadmap/beginner/04-secure-tool-and-action-interface-design", "Reading", "README · needs focused lab, notebook, tests"),
  road("F05", "05", "Foundation", "Authorization, approval, and least privilege", "roadmap/beginner/05-authorization-approval-and-least-privilege", "Reading", "README · needs focused lab, notebook, tests"),
  road("F06", "06", "Foundation", "Prompt injection and untrusted content", "roadmap/beginner/06-prompt-injection-and-untrusted-content", "Reading", "README · needs focused lab, notebook, tests"),
  road("F07", "07", "Foundation", "Context and evidence security", "roadmap/beginner/07-context-and-evidence-security", "Reading", "README · needs lab, notebook, tests"),
  road("I01", "01", "State & execution", "Agent memory security", "roadmap/intermediate/01-agent-memory-security", "Pilot", "README · lab · notebook · needs deeper tests"),
  road("I02", "02", "State & execution", "Checkpoint and durable execution security", "roadmap/intermediate/02-state-checkpoint-and-durable-execution-security", "Pilot", "README · notebook · needs course adapter and tests"),
  road("I03", "03", "State & execution", "Agent identity and delegated authority", "roadmap/intermediate/03-agent-identity-and-delegated-authority", "Planned", "Release contract · needs lab, notebook, tests"),
  road("I04", "04", "State & execution", "Secrets and credential security", "roadmap/intermediate/04-secrets-and-credential-security", "Pilot", "README · lab · needs notebook and tests"),
  road("I05", "05", "State & execution", "Filesystem, execution, and sandbox security", "roadmap/intermediate/05-filesystem-code-execution-and-sandbox-security", "Planned", "Release contract · needs lab, notebook, tests"),
  road("I06", "06", "State & execution", "Network egress, SSRF, and resources", "roadmap/intermediate/06-network-egress-ssrf-and-external-resource-security", "Pilot", "README · lab · notebook · needs deeper tests"),
  road("I07", "07", "State & execution", "Tool-result and output poisoning", "roadmap/intermediate/07-tool-result-and-output-poisoning", "Pilot", "README · lab · needs notebook and tests"),
  road("I08", "08", "State & execution", "Agentic RAG security", "roadmap/intermediate/08-agentic-rag-security", "Planned", "Release contract · needs lab, notebook, tests"),
  road("I09", "09", "State & execution", "MCP security", "roadmap/intermediate/09-mcp-security", "Pilot", "README · lab · notebook · needs protocol update and tests"),
  road("I10", "10", "State & execution", "Human-in-the-loop security", "roadmap/intermediate/10-human-in-the-loop-security", "Planned", "Release contract · needs lab, notebook, tests"),
  road("A01", "01", "Distributed adversaries", "Multi-agent delegation security", "roadmap/advanced/01-multi-agent-delegation-security", "Pilot", "README · notebook · needs course adapter and tests"),
  road("A02", "02", "Distributed adversaries", "Cross-agent injection and message poisoning", "roadmap/advanced/02-cross-agent-prompt-injection-and-message-poisoning", "Planned", "Release contract · needs lab, notebook, tests"),
  road("A03", "03", "Distributed adversaries", "Cascading failures and blast radius", "roadmap/advanced/03-cascading-failures-and-blast-radius-control", "Planned", "Release contract · needs lab, notebook, tests"),
  road("A04", "04", "Distributed adversaries", "Agent-to-agent (A2A) security", "roadmap/advanced/04-agent-to-agent-a2a-security", "Planned", "A2A 1.0 contract · needs lab, notebook, tests"),
  road("A05", "05", "Distributed adversaries", "Protocol composition security", "roadmap/advanced/05-protocol-composition-security", "Planned", "Release contract · needs lab, notebook, tests"),
  road("A06", "06", "Distributed adversaries", "Agent supply-chain security", "roadmap/advanced/06-agent-supply-chain-security", "Planned", "SLSA-aligned contract · needs lab, notebook, tests"),
  road("A07", "07", "Distributed adversaries", "Agent security testing and fuzzing", "roadmap/advanced/07-agent-security-testing-and-fuzzing", "Planned", "Release contract · needs lab, notebook, tests"),
  road("A08", "08", "Distributed adversaries", "Red teaming and adversarial evaluation", "roadmap/advanced/08-agent-red-teaming-and-adversarial-evaluation", "Pilot", "README · lab · notebook · needs deeper tests"),
  road("A09", "09", "Distributed adversaries", "Observability and runtime assurance", "roadmap/advanced/09-agent-security-observability-and-runtime-assurance", "Planned", "Release contract · needs lab, notebook, tests"),
  road("A10", "10", "Distributed adversaries", "Threat hunting and anomaly detection", "roadmap/advanced/10-threat-hunting-and-behavioral-anomaly-detection", "Planned", "Release contract · needs lab, notebook, tests"),
  road("E01", "01", "Enterprise operations", "Secure long-running agents", "roadmap/enterprise/01-secure-long-running-agents", "Planned", "Release contract · needs lab, notebook, tests"),
  road("E02", "02", "Enterprise operations", "Kill switches and safe degradation", "roadmap/enterprise/02-kill-switches-revocation-and-safe-degradation", "Pilot", "README · notebook · needs course adapter and tests"),
  road("E03", "03", "Enterprise operations", "Incident detection and containment", "roadmap/enterprise/03-agent-incident-detection-and-containment", "Pilot", "README · notebook · needs course adapter and tests"),
  road("E04", "04", "Enterprise operations", "Forensics, recovery, and safe replay", "roadmap/enterprise/04-agent-forensics-recovery-and-safe-replay", "Planned", "Release contract · needs lab, notebook, tests"),
  road("E05", "05", "Enterprise operations", "Release gates and production readiness", "roadmap/enterprise/05-security-release-gates-and-production-readiness", "Planned", "Release contract · needs lab, notebook, tests"),
  road("E06", "06", "Enterprise operations", "Agent security governance", "roadmap/enterprise/06-agent-security-governance", "Pilot", "README · lab · notebook · needs deeper tests"),
  road("E07", "07", "Enterprise operations", "Enterprise security architecture", "roadmap/enterprise/07-enterprise-agent-security-architecture", "Planned", "Release contract · needs lab, notebook, tests"),
  road("E08", "08", "Enterprise operations", "Architecture review workshop", "roadmap/enterprise/08-agent-security-architecture-review-workshop", "Planned", "Release contract · needs lab, notebook, tests"),
  road("E09", "09", "Enterprise operations", "Production secure-agent capstone", "roadmap/enterprise/09-production-secure-agent-capstone", "Pilot", "README · lab · needs notebook and integrated tests"),
];
