export const lessons = [
 {id:"b1",level:"Beginner",step:"01",title:"Security foundations",summary:"Map assets, actors, trust boundaries, and blast radius.",material:"docs/security-foundations.md",lab:"labs/beginner/01_tool_policy.py",outcome:"Draw a threat model and place controls at the correct boundary.",refs:["docs/security-foundations.md","https://www.nist.gov/artificial-intelligence/ai-agent-standards-initiative"]},
 {id:"b2",level:"Beginner",step:"02",title:"Prompt injection",summary:"Recognize untrusted instructions in documents, tools, and memory.",material:"docs/prompt-injection-and-mcp.md",lab:"labs/beginner/02_prompt_injection.py",outcome:"Contain untrusted content without granting it authority.",refs:["docs/prompt-injection-and-mcp.md","https://atlas.mitre.org/"]},
 {id:"b3",level:"Beginner",step:"03",title:"Secure research agent",summary:"Combine narrow tools, evidence checks, and policy boundaries in a safe capstone.",material:"docs/secure-agent-capstone.md",lab:"labs/beginner/03_secure_research_agent.py",notebook:"labs/notebooks/03_secure_research_agent.ipynb",outcome:"Build a useful research assistant that treats retrieved text as untrusted data.",refs:["docs/secure-agent-capstone.md","https://genai.owasp.org/resource/securing-agentic-applications-guide-1-0/"]},
 {id:"i1",level:"Intermediate",step:"01",title:"Identity and memory",summary:"Propagate identity and secure state, memory, and tenant boundaries.",material:"docs/tools-identity-and-memory.md",lab:"labs/intermediate/01_identity_propagation.py",outcome:"Enforce down-scoped authorization and safe memory writes.",refs:["docs/tools-identity-and-memory.md","https://cloud.google.com/blog/products/identity-security/cloud-ciso-perspectives-practical-guidance-building-with-saif"]},
 {id:"i2",level:"Intermediate",step:"02",title:"MCP gateway security",summary:"Secure tool discovery, scopes, transports, and audit trails.",material:"docs/prompt-injection-and-mcp.md",lab:"labs/intermediate/02_mcp_gateway.py",outcome:"Design a gateway that authenticates, scopes, rate-limits, and audits tool calls.",refs:["https://modelcontextprotocol.io/docs/tutorials/security/security_best_practices","https://cheatsheetseries.owasp.org/cheatsheets/MCP_Security_Cheat_Sheet.html"]},
 {id:"i3",level:"Intermediate",step:"03",title:"Incident response and recovery",summary:"Contain suspicious runs, recover safely, and prevent unsafe retries.",material:"docs/incident-response-and-recovery.md",lab:"labs/intermediate/03_incident_recovery.py",outcome:"Pause, investigate, and replay side effects with idempotency and evidence.",refs:["docs/incident-response-and-recovery.md","https://cloud.google.com/use-cases/secure-ai-framework"]},
 {id:"a1",level:"Advanced",step:"01",title:"Security evaluation",summary:"Turn attack cases into release gates and measurable evidence.",material:"docs/production-and-evaluation.md",lab:"labs/advanced/01_attack_evaluation.py",outcome:"Block unsafe releases using reproducible trajectory and policy tests.",refs:["https://genai.owasp.org/initiatives/agentic-security-initiative/","https://atlas.mitre.org/"]},
 {id:"a2",level:"Advanced",step:"02",title:"Multi-agent security",summary:"Constrain delegation, roles, messages, and cascading failure.",material:"docs/production-and-evaluation.md",lab:"labs/advanced/02_multi_agent_security.py",outcome:"Down-scope delegated authority and preserve accountability across a team.",refs:["https://www.nist.gov/artificial-intelligence/ai-agent-standards-initiative","https://learn.microsoft.com/en-us/agent-framework/agents/safety"]},
 {id:"a3",level:"Advanced",step:"03",title:"Governance and production readiness",summary:"Turn threat models, evaluations, and rollback drills into release gates.",material:"docs/governance-and-production-readiness.md",lab:"labs/advanced/03_production_gate.py",outcome:"Approve autonomy only when measurable safety evidence and ownership are present.",refs:["docs/governance-and-production-readiness.md","https://atlas.mitre.org/"]}
];

export const checks = {
  b1: ["Where does authorization belong?", "At the application and tool boundary, outside model instructions."],
  b2: ["What is indirect prompt injection?", "Untrusted instructions arriving through documents, tools, memory, or other content."],
  i1: ["What should identity propagation preserve?", "The user, tenant, resource, operation, and down-scoped permissions."],
  i2: ["What must an MCP gateway enforce?", "Authentication, scopes, schema validation, rate limits, and auditability."],
  a1: ["What proves a security control works?", "Reproducible attack cases, policy decisions, traces, and release-gate evidence."],
  a2: ["How should delegation be constrained?", "Explicit roles, parent authority, typed messages, budgets, and termination rules."],
  b3: ["Can retrieved text authorize a tool call?", "No. Retrieved content is untrusted data; application policy must authorize tools."],
  i3: ["Why is idempotency important during recovery?", "It prevents an uncertain side effect from being applied twice when a run is replayed."],
  a3: ["What should block a production release?", "Missing threat-model evidence, policy/attack tests, rollback readiness, or accountable ownership."]
};
