export const lessons = [
 {id:"b1",level:"Beginner",step:"01",title:"Security foundations",summary:"Map assets, actors, trust boundaries, and blast radius.",description:"Identify what an agent must protect, where trust changes, and how least privilege, budgets, approvals, and stop conditions reduce blast radius.",material:"docs/security-foundations.md",lab:"labs/beginner/01_tool_policy.py",outcome:"Draw a threat model and place controls at the correct boundary.",refs:["docs/security-foundations.md","https://www.nist.gov/artificial-intelligence/ai-agent-standards-initiative"]},
 {id:"b2",level:"Beginner",step:"02",title:"Prompt injection",summary:"Recognize untrusted instructions in documents, tools, and memory.",description:"Understand direct and indirect prompt injection, provenance, instruction/data separation, and why a prompt is not an authorization boundary.",material:"docs/prompt-injection-and-mcp.md",lab:"labs/beginner/02_prompt_injection.py",outcome:"Contain untrusted content without granting it authority.",refs:["docs/prompt-injection-and-mcp.md","https://atlas.mitre.org/"]},
 {id:"b3",level:"Beginner",step:"03",title:"Secure research agent",summary:"Combine narrow tools, evidence checks, and policy boundaries in a safe capstone.",description:"Build a research assistant that ranks evidence, filters poisoned documents, refuses unsafe capabilities, returns citations, and records an audit event.",material:"docs/secure-agent-capstone.md",lab:"labs/beginner/03_secure_research_agent.py",notebook:"labs/notebooks/03_secure_research_agent.ipynb",outcome:"Build a useful research assistant that treats retrieved text as untrusted data.",refs:["docs/secure-agent-capstone.md","https://genai.owasp.org/resource/securing-agentic-applications-guide-1-0/"]},
 {id:"i1",level:"Intermediate",step:"01",title:"Identity and memory",summary:"Propagate identity and secure state, memory, and tenant boundaries.",description:"Trace user, tenant, resource, operation, and delegated scope across a tool call. Learn why memory needs classification, expiry, and provenance.",material:"docs/tools-identity-and-memory.md",lab:"labs/intermediate/01_identity_propagation.py",outcome:"Enforce down-scoped authorization and safe memory writes.",refs:["docs/tools-identity-and-memory.md","https://cloud.google.com/blog/products/identity-security/cloud-ciso-perspectives-practical-guidance-building-with-saif"]},
 {id:"i2",level:"Intermediate",step:"02",title:"MCP gateway security",summary:"Secure tool discovery, scopes, transports, and audit trails.",description:"Design a gateway that authenticates clients, allowlists tools, validates schemas, limits rate and egress, and audits every call.",material:"docs/prompt-injection-and-mcp.md",lab:"labs/intermediate/02_mcp_gateway.py",outcome:"Design a gateway that authenticates, scopes, rate-limits, and audits tool calls.",refs:["https://modelcontextprotocol.io/docs/tutorials/security/security_best_practices","https://cheatsheetseries.owasp.org/cheatsheets/MCP_Security_Cheat_Sheet.html"]},
 {id:"i3",level:"Intermediate",step:"03",title:"Incident response and recovery",summary:"Contain suspicious runs, recover safely, and prevent unsafe retries.",description:"Practice revocation, human approval, checkpoints, and idempotent replay after a suspicious connector argument.",material:"docs/incident-response-and-recovery.md",lab:"labs/intermediate/03_incident_recovery.py",outcome:"Pause, investigate, and replay side effects with idempotency and evidence.",refs:["docs/incident-response-and-recovery.md","https://cloud.google.com/use-cases/secure-ai-framework"]},
 {id:"a1",level:"Advanced",step:"01",title:"Security evaluation",summary:"Turn attack cases into release gates and measurable evidence.",description:"Build a reproducible attack matrix and evaluate trajectories and traceability rather than only final answers.",material:"docs/production-and-evaluation.md",lab:"labs/advanced/01_attack_evaluation.py",outcome:"Block unsafe releases using reproducible trajectory and policy tests.",refs:["https://genai.owasp.org/initiatives/agentic-security-initiative/","https://atlas.mitre.org/"]},
 {id:"a2",level:"Advanced",step:"02",title:"Multi-agent security",summary:"Constrain delegation, roles, messages, and cascading failure.",description:"Define parent authority, typed messages, isolated state, budgets, termination, and accountability for delegated workers.",material:"docs/production-and-evaluation.md",lab:"labs/advanced/02_multi_agent_security.py",outcome:"Down-scope delegated authority and preserve accountability across a team.",refs:["https://www.nist.gov/artificial-intelligence/ai-agent-standards-initiative","https://learn.microsoft.com/en-us/agent-framework/agents/safety"]},
 {id:"a3",level:"Advanced",step:"03",title:"Governance and production readiness",summary:"Turn threat models, evaluations, and rollback drills into release gates.",description:"Review weighted evidence gates and runtime metrics before approving autonomy, canaries, kill switches, and rollback ownership.",material:"docs/governance-and-production-readiness.md",lab:"labs/advanced/03_production_gate.py",outcome:"Approve autonomy only when measurable safety evidence and ownership are present.",refs:["docs/governance-and-production-readiness.md","https://atlas.mitre.org/"]}
];

export const checks = Object.fromEntries([
 ["b1","Where does authorization belong?",["In a prompt only","At the application and tool boundary","Inside retrieved documents"],1,"Application code must enforce identity, permissions, and side-effect policy."],
 ["b2","What is indirect prompt injection?",["A policy decision","Untrusted instructions in documents, tools, or memory","A schema error"],1,"External content can contain instructions, but remains untrusted data."],
 ["b3","Can retrieved text authorize a tool call?",["Yes","No; application policy must authorize tools","Only with a URL"],1,"Evidence can support an answer, never grant capability."],
 ["i1","What should identity propagation preserve?",["Only model name","User, tenant, resource, operation, and scope","Previous conversation forever"],1,"Authorization is contextual and must not widen during delegation."],
 ["i2","What must an MCP gateway enforce?",["Trust discovery","Authentication, scopes, schema validation, limits, and auditability","Only descriptions"],1,"Discovery is metadata, not trust; every call needs controls."],
 ["i3","Why is idempotency important?",["It improves prompts","It prevents an uncertain side effect twice","It replaces authorization"],1,"Replay with the same key must not duplicate external work."],
 ["a1","What proves a control works?",["Fluent prose","Reproducible attacks, decisions, traces, and release evidence","A larger model"],1,"Security claims need repeatable tests and observable trajectories."],
 ["a2","How should delegation be constrained?",["Shared unrestricted credentials","Roles, parent authority, typed messages, budgets, and termination","No audit"],1,"Workers need narrower authority and accountable contracts."],
 ["a3","What should block a production release?",["Missing rollback readiness or ownership","A style preference","A green demo"],0,"Missing safety evidence, rollback, or ownership is a blocker."]
].map(([id,prompt,options,correct,explanation])=>[id,{prompt,options,correct,explanation}]));
